apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - port: 5432
      targetPort: 5432
